import type { NextConfig } from "next"

const supabaseHost = process.env.NEXT_PUBLIC_SUPABASE_URL
  ? new URL(process.env.NEXT_PUBLIC_SUPABASE_URL).hostname
  : undefined

/**
 * Turnstile menuntut TIGA izin sekaligus, dan melewatkan salah satunya
 * membuatnya gagal tanpa suara: skripnya, iframe tempat tantangan digambar,
 * dan koneksi balik ke Cloudflare. Tanpa frame-src khususnya, iframe-nya jatuh
 * ke `default-src 'self'` dan kotak verifikasi tidak pernah muncul — pengguna
 * sah yang tertandai mencurigakan akan terjebak permanen tanpa jalan keluar,
 * karena satu-satunya cara melanjutkan justru yang diblokir.
 *
 * Host-nya hanya ditambahkan bila Turnstile memang dikonfigurasi, mengikuti
 * cara supabaseHost diperlakukan di atas: pemasangan tanpa Turnstile tidak
 * mengumumkan pihak ketiga yang tidak pernah dihubunginya.
 */
const turnstileHost = process.env.NEXT_PUBLIC_TURNSTILE_SITE_KEY
  ? "https://challenges.cloudflare.com"
  : ""

/**
 * CSP (PRD §9.4).
 *
 * `script-src` HARUS ditulis eksplisit dengan 'unsafe-inline'. Menghilangkannya
 * membuat browser jatuh ke `default-src 'self'`, dan itu memblokir seluruh
 * skrip inline hidrasi Next.js — halaman tetap tampil (HTML-nya sudah dirender
 * server) tetapi mati total: formulir tidak mengirim, peta tidak muncul, hero
 * 3D tidak jalan. Terverifikasi lewat uji browser, bukan dugaan.
 *
 * 'unsafe-inline' pada script-src memang TIDAK memberi perlindungan XSS yang
 * berarti. Alternatif yang benar adalah nonce per-permintaan lewat middleware,
 * tetapi nonce memaksa setiap halaman menjadi dinamis dan mematikan ISR 5 menit
 * yang menjadi strategi performa §16.1. Kompromi ini dicatat sebagai utang
 * teknis di docs/RUNBOOK.md, bukan disamarkan sebagai keamanan.
 *
 * Arahan lain di bawah ini benar-benar berlaku dan itulah nilai CSP di sini:
 * dari mana gambar boleh dimuat, ke mana browser boleh terhubung, ke mana
 * formulir boleh dikirim, dan siapa boleh membingkai halaman ini.
 */
const csp = [
  "default-src 'self'",
  // Wajib eksplisit — lihat catatan di atas. va.vercel-scripts.com adalah
  // @vercel/analytics yang sudah terpasang di layout.tsx; tanpa host ini
  // skripnya diblokir dan analitik mati diam-diam.
  // 'wasm-unsafe-eval' dibutuhkan dekoder meshopt pada hero 3D
  // (public/models/*.glb dioptimalkan dengan meshopt, dekodernya WebAssembly).
  // Ini izin sempit khusus WASM — TIDAK membuka eval() umum.
  // 'unsafe-eval' dibutuhkan React di development mode untuk fitur debugging
  // seperti rekonstruksi callstack. TIDAK diikutkan di production.
  `script-src 'self' 'unsafe-inline' 'wasm-unsafe-eval'${process.env.NODE_ENV === "development" ? " 'unsafe-eval'" : ""} https://va.vercel-scripts.com${turnstileHost ? ` ${turnstileHost}` : ""}`,
  `img-src 'self' data: blob: https://*.tile.openstreetmap.org${supabaseHost ? ` https://${supabaseHost}` : ""}`,
  // blob: dibutuhkan loader GLTF/meshopt hero 3D (membuat object URL untuk
  // worker dan buffer geometri).
  `connect-src 'self' blob: https://va.vercel-scripts.com${supabaseHost ? ` https://${supabaseHost} wss://${supabaseHost}` : ""}${turnstileHost ? ` ${turnstileHost}` : ""}`,
  "style-src 'self' 'unsafe-inline'", // Tailwind + style inline Leaflet
  "font-src 'self' data:",
  "worker-src 'self' blob:",
  // Tanpa arahan ini, frame apa pun jatuh ke default-src 'self'. Widget
  // Turnstile adalah iframe lintas-asal, jadi ia harus disebut eksplisit.
  `frame-src 'self'${turnstileHost ? ` ${turnstileHost}` : ""}`,
  "object-src 'none'",
  "base-uri 'self'",
  "form-action 'self'",
  "frame-ancestors 'none'",
  "upgrade-insecure-requests",
].join("; ")

const nextConfig: NextConfig = {
  images: {
    remotePatterns: supabaseHost
      ? [{ protocol: "https", hostname: supabaseHost, pathname: "/storage/v1/object/public/**" }]
      : [],
  },

  async headers() {
    return [
      {
        // The optimised model is regenerated by `npm run model:optimize` and
        // committed, so its contents only change when the filename's commit
        // does — it can be cached hard.
        source: "/models/:path*",
        headers: [{ key: "Cache-Control", value: "public, max-age=31536000, immutable" }],
      },
      {
        source: "/:path*",
        headers: [
          { key: "Content-Security-Policy", value: csp },
          { key: "X-Content-Type-Options", value: "nosniff" },
          { key: "Referrer-Policy", value: "strict-origin-when-cross-origin" },
          { key: "X-Frame-Options", value: "DENY" },
          { key: "Permissions-Policy", value: "camera=(), microphone=(), payment=()" },
        ],
      },
    ]
  },
}

export default nextConfig
